// Do not edit. This file is machine generated by the Resource DLL Wizard.

library SyntaxDiag;

{ITE} {DFMFileType} {forms\FCanvasSizeSettings.dfm}
{ITE} {DFMFileType} {forms\FHtmlView.dfm}
{ITE} {DFMFileType} {Main.dfm}
{ITE} {RCFileType} {Win32\Debug\SyntaxDiag_DRC.rc}

{$R 'forms\FCanvasSizeSettings.dfm' 'FCanvasSettings:TForm'}
{$R 'forms\FHtmlView.dfm' 'FHtml:TForm'}
{$R 'Main.dfm' 'EditorForm:TForm'}
{$R 'Win32\Debug\SyntaxDiag_DRC.res' 'Win32\Debug\SyntaxDiag_DRC.rc'}

{$E RUS}

begin
end.
