unit Data.InitData;

interface
const
  Tolerance = 5; // Кол-во пискелей, на которые юзеру можно "промахнуться"
  NearFigure = 20; // Количество пикселей, при котором идет "присоединение" фигуры;
  step_round = 20; // "Шаг сетки"
  Default_LineSVG_Width = 2; // Ширина линии в SVG
  Font_Size = 8; // Размер шрифта

resourcestring // Работа с файлами:
  rsNewFileDlg = 'Вы уверены? Все несохраненные данные будут удалены. Продолжить?';
  rsNewFile = 'Новый файл';
  rsExitDlg = 'Вы внесли изменения.. А не хотите ли Вы сохраниться перед тем, как выйти?';
  rsInvalidFile = 'Вы пытаетесь открыть какой-то непонятный файл. Пожалуйста, используйте только файлы, созданные этой программой!';
  rsTrashFile = 'Файл поврежден!';
resourcestring // Раздел помощи
  rsHelpHowIsSD_Caption = 'Что такое синтаксическая диаграмма?';
  rsHelp_Caption = 'Помощь';
  // Название ресурсов
  rsHelpHowIsSD_ResName = 'help1';
  rsHelp_ResName = 'help2';
resourcestring
  rsInputError = 'Ошибка ввода';
  rsInputBigSizes = 'Введенные размеры слишком большие и могут вызвать переполнение первичного рабочего диска';

 const // Смена языка
  SRuChangeLangMsg = 'Язык изменен. Для того, чтобы он обновился, перезапустите приложение';
  SEnChangeLangMsg = 'The language is changed. In order for it to be updated, restart the application';

Const
  SGeneratedText = '<!-- ################################################################ -->' + #10#13 + '<!-- This Syntax Diagram generated by BrakhMen Syntax Diagrams Editor -->' + #10#13 + '<!-- Site : http://brakh.men -->' + #10#13 + '<!-- ################################################################ -->';
  // ### VIEW PART CONSTANTS ###
const
  VertRad = 3; // Радиус вершины

  Arrow_Width = 20; // Ширина "дюбки" стрелки
  Arrow_Height = 10; // Высота стрелки

  Lines_Width = 2; // ширина линии стрелки
  Lines_Deg = 15; // Высота диагонального "среза"
  Lines_DegLenght = 15; // Ширина диагонального "среза"
implementation

end.
